"use client";

import {
  Speed as SpeedIcon,
  Memory as MemoryIcon,
  DeveloperBoard as GpuIcon,
  Settings as SettingsIcon,
  Tune as TuneIcon,
  Layers as LayersIcon,
  Image as ImageIcon,
} from "@mui/icons-material";
import type { ConfigType, FieldDefinition, SectionGroup, ValidationRule } from "./types";

// Section groups for accordion organization
export const sectionGroups: Record<
  ConfigType,
  SectionGroup[]
> = {
  sampling: [
    {
      title: "Échantillonnage Principal",
      icon: <SpeedIcon />,
      fields: ["temperature", "top_k", "top_p", "min_p", "typical_p"],
    },
    {
      title: "Contrôle de Répétition",
      icon: <TuneIcon />,
      fields: [
        "repeat_last_n",
        "repeat_penalty",
        "presence_penalty",
        "frequency_penalty",
        "dry_multiplier",
        "dry_base",
        "dry_allowed_length",
        "dry_penalty_last_n",
        "dry_sequence_breaker",
      ],
    },
    {
      title: "Échantillonnage Avancé",
      icon: <SettingsIcon />,
      fields: [
        "mirostat",
        "mirostat_eta",
        "mirostat_tau",
        "dynatemp_range",
        "dynatemp_exponent",
        "top_nsigma",
        "xtc_probability",
        "xtc_threshold",
      ],
    },
    {
      title: "Contraintes de Sortie",
      icon: <LayersIcon />,
      fields: [
        "samplers",
        "sampler_seq",
        "seed",
        "grammar",
        "grammar_file",
        "json_schema",
        "json_schema_file",
        "ignore_eos",
        "escape",
      ],
    },
    {
      title: "Extension de Contexte (ROPE)",
      icon: <MemoryIcon />,
      fields: [
        "rope_scaling_type",
        "rope_scale",
        "rope_freq_base",
        "rope_freq_scale",
        "yarn_orig_ctx",
        "yarn_ext_factor",
        "yarn_attn_factor",
        "yarn_beta_slow",
        "yarn_beta_fast",
      ],
    },
    {
      title: "Performance",
      icon: <SpeedIcon />,
      fields: ["flash_attn", "logit_bias"],
    },
  ],
  memory: [
    {
      title: "Paramètres de Cache",
      icon: <MemoryIcon />,
      fields: ["cache_ram", "cache_type_k", "cache_type_v"],
    },
    {
      title: "Gestion de la Mémoire",
      icon: <SettingsIcon />,
      fields: ["mmap", "mlock", "numa", "defrag_thold"],
    },
  ],
  gpu: [
    {
      title: "Sélection de Périphérique",
      icon: <GpuIcon />,
      fields: ["device", "list_devices"],
    },
    {
      title: "Configuration GPU",
      icon: <SettingsIcon />,
      fields: ["gpu_layers", "split_mode", "tensor_split", "main_gpu", "kv_offload"],
    },
    {
      title: "Options de Performance",
      icon: <SpeedIcon />,
      fields: ["repack", "no_host"],
    },
  ],
  advanced: [
    {
      title: "Comportement du Modèle",
      icon: <SettingsIcon />,
      fields: [
        "swa_full",
        "override_tensor",
        "cpu_moe",
        "n_cpu_moe",
        "kv_unified",
        "pooling",
        "context_shift",
      ],
    },
    {
      title: "Calcul Distribué",
      icon: <GpuIcon />,
      fields: ["rpc", "offline", "override_kv", "op_offload"],
    },
    {
      title: "Ajustement du Modèle",
      icon: <TuneIcon />,
      fields: ["fit", "fit_target", "fit_ctx", "check_tensors"],
    },
    {
      title: "Gestion des Ressources",
      icon: <MemoryIcon />,
      fields: ["sleep_idle_seconds", "polling", "polling_batch"],
    },
    {
      title: "Raisonnement",
      icon: <LayersIcon />,
      fields: ["reasoning_format_value_format", "reasoning_budget", "custom_params"],
    },
  ],
  lora: [
    {
      title: "Adaptateurs LoRA",
      icon: <LayersIcon />,
      fields: ["lora", "lora_scaled"],
    },
    {
      title: "Vecteurs de Contrôle",
      icon: <TuneIcon />,
      fields: [
        "control_vector",
        "control_vector_scaled",
        "control_vector_layer_range",
      ],
    },
    {
      title: "Décodage Spéculatif",
      icon: <SpeedIcon />,
      fields: [
        "model_draft",
        "model_url_draft",
        "ctx_size_draft",
        "threads_draft",
        "threads_batch_draft",
        "draft_max",
        "draft_min",
        "draft_p_min",
      ],
    },
    {
      title: "Cache du Modèle de Brouillon",
      icon: <MemoryIcon />,
      fields: [
        "cache_type_k_draft",
        "cache_type_v_draft",
        "cpu_moe_draft",
        "n_cpu_moe_draft",
        "n_gpu_layers_draft",
        "device_draft",
      ],
    },
    {
      title: "Options de Décodage Spéculatif",
      icon: <SettingsIcon />,
      fields: ["spec_replace"],
    },
  ],
  multimodal: [
    {
      title: "Projection Visuelle",
      icon: <ImageIcon />,
      fields: ["mmproj", "mmproj_url", "mmproj_auto", "mmproj_offload"],
    },
    {
      title: "Traitement d'Images",
      icon: <SettingsIcon />,
      fields: ["image_min_tokens", "image_max_tokens"],
    },
  ],
};

// Validation rules for different fields
export const validationRules: Record<string, ValidationRule> = {
  temperature: { min: 0, max: 2, required: false },
  top_k: { min: 1, max: 100, required: false },
  top_p: { min: 0, max: 1, required: false },
  min_p: { min: 0, max: 0.5, required: false },
  top_nsigma: { min: 0, max: 3, required: false },
  xtc_probability: { min: 0, max: 1, required: false },
  xtc_threshold: { min: 0, max: 1, required: false },
  typical_p: { min: 0.1, max: 1, required: false },
  repeat_last_n: { min: 0, max: 2048, required: false },
  repeat_penalty: { min: 1, max: 2, required: false },
  presence_penalty: { min: 0, max: 2, required: false },
  frequency_penalty: { min: 0, max: 2, required: false },
  dry_multiplier: { min: 0, max: 5, required: false },
  dry_base: { min: 1, max: 3, required: false },
  dry_allowed_length: { min: 0, max: 10, required: false },
  dry_penalty_last_n: { min: 0, max: 512, required: false },
  dynatemp_range: { min: 0, max: 2, required: false },
  dynatemp_exponent: { min: 0.1, max: 2, required: false },
  mirostat: { min: 0, max: 2, required: false },
  mirostat_eta: { min: 0.001, max: 1, required: false },
  mirostat_tau: { min: 0, max: 10, required: false },
  seed: { min: -1, max: Number.MAX_SAFE_INTEGER, required: false },
  rope_scale: { min: 0, max: 10, required: false },
  rope_freq_base: { min: 0, max: 1000000, required: false },
  rope_freq_scale: { min: 0, max: 10, required: false },
  yarn_orig_ctx: { min: 0, max: 32768, required: false },
  yarn_ext_factor: { min: -1, max: 16, required: false },
  yarn_attn_factor: { min: 0, max: 4, required: false },
  yarn_beta_slow: { min: 0, max: 10, required: false },
  yarn_beta_fast: { min: 0, max: 100, required: false },
  cache_ram: { min: 0, max: 128, required: false },
  defrag_thold: { min: -1, max: 1, required: false },
  gpu_layers: { min: -1, max: 1000, required: false },
  main_gpu: { min: 0, max: 16, required: false },
  kv_offload: { min: 0, max: 1, required: false },
  n_cpu_moe: { min: 0, max: 64, required: false },
  n_cpu_moe_draft: { min: 0, max: 32, required: false },
  n_gpu_layers_draft: { min: -1, max: 1000, required: false },
  fit_target: { min: 0, max: 100, required: false },
  fit_ctx: { min: 0, max: 32768, required: false },
  sleep_idle_seconds: { min: 0, max: 3600, required: false },
  reasoning_budget: { min: 0, max: 8192, required: false },
  ctx_size_draft: { min: 512, max: 16384, required: false },
  draft_max: { min: 1, max: 64, required: false },
  draft_min: { min: 1, max: 32, required: false },
  draft_p_min: { min: 0, max: 0.5, required: false },
  image_min_tokens: { min: 0, max: 8192, required: false },
  image_max_tokens: { min: 0, max: 8192, required: false },
};

// Field definitions for each config type
export const configFields: Record<ConfigType, FieldDefinition[]> = {
  sampling: [
    {
      name: "temperature",
      label: "Température",
      type: "number",
      defaultValue: 0.7,
      xs: 12,
      sm: 6,
      unit: "",
      step: 0.01,
      marks: [
        { value: 0, label: "0" },
        { value: 1, label: "1" },
        { value: 2, label: "2" },
      ],
    },
    { name: "top_k", label: "Top K", type: "number", defaultValue: 40, xs: 12, sm: 6, unit: "", step: 1 },
    {
      name: "top_p",
      label: "Top P",
      type: "number",
      defaultValue: 0.9,
      xs: 12,
      sm: 6,
      unit: "",
      step: 0.01,
      marks: [
        { value: 0, label: "0" },
        { value: 1, label: "1" },
      ],
    },
    { name: "min_p", label: "Min P", type: "number", defaultValue: 0.05, xs: 12, sm: 6, unit: "", step: 0.01 },
    { name: "top_nsigma", label: "Top N Sigma", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
    {
      name: "xtc_probability",
      label: "Probabilité XTC",
      type: "number",
      defaultValue: 0,
      xs: 12,
      sm: 6,
      unit: "",
      step: 0.01,
      marks: [
        { value: 0, label: "0" },
        { value: 1, label: "1" },
      ],
    },
    { name: "xtc_threshold", label: "Seuil XTC", type: "number", defaultValue: 0.1, xs: 12, sm: 6, unit: "", step: 0.01 },
    {
      name: "typical_p",
      label: "Typical P",
      type: "number",
      defaultValue: 1,
      xs: 12,
      sm: 6,
      unit: "",
      step: 0.01,
      marks: [
        { value: 0, label: "0" },
        { value: 1, label: "1" },
      ],
    },
    {
      name: "repeat_last_n",
      label: "Répéter Dernier N",
      type: "number",
      defaultValue: 64,
      xs: 12,
      sm: 6,
      unit: "tokens",
      step: 1,
    },
    {
      name: "repeat_penalty",
      label: "Pénalité de Répétition",
      type: "number",
      defaultValue: 1,
      xs: 12,
      sm: 6,
      unit: "",
      step: 0.01,
      marks: [
        { value: 1, label: "1.0" },
        { value: 1.5, label: "1.5" },
        { value: 2, label: "2.0" },
      ],
    },
    { name: "presence_penalty", label: "Pénalité de Présence", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
    { name: "frequency_penalty", label: "Pénalité de Fréquence", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
    { name: "dry_multiplier", label: "Multiplicateur DRY", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
    { name: "dry_base", label: "Base DRY", type: "number", defaultValue: 1.75, xs: 12, sm: 6, unit: "", step: 0.01 },
    {
      name: "dry_allowed_length",
      label: "Longueur Autorisée DRY",
      type: "number",
      defaultValue: 2,
      xs: 12,
      sm: 6,
      unit: "tokens",
      step: 1,
    },
    {
      name: "dry_penalty_last_n",
      label: "Pénalité Dernier N DRY",
      type: "number",
      defaultValue: 0,
      xs: 12,
      sm: 6,
      unit: "tokens",
      step: 1,
    },
    { name: "dry_sequence_breaker", label: "Séparateur de Séquence DRY", type: "text", defaultValue: "\\n, !, ., ?", xs: 12, sm: 6 },
    { name: "dynatemp_range", label: "Plage Dynatemp", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
    { name: "dynatemp_exp", label: "Exp Dynatemp", type: "number", defaultValue: 1, xs: 12, sm: 6, unit: "", step: 0.1 },
    { name: "mirostat", label: "Mirostat", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 1 },
    { name: "mirostat_lr", label: "LR Mirostat", type: "number", defaultValue: 0.1, xs: 12, sm: 6, unit: "", step: 0.01 },
    { name: "mirostat_ent", label: "Ent Mirostat", type: "number", defaultValue: 5, xs: 12, sm: 6, unit: "", step: 0.1 },
    { name: "samplers", label: "Échantillonneurs", type: "text", defaultValue: "", xs: 12 },
    { name: "sampler_seq", label: "Séquence d'Échantillonnage", type: "text", defaultValue: "", xs: 12 },
    { name: "seed", label: "Graine", type: "number", defaultValue: -1, xs: 12, sm: 6, unit: "", step: 1 },
    { name: "grammar", label: "Grammaire", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "grammar_file", label: "Fichier de Grammaire", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "json_schema", label: "Schéma JSON", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "json_schema_file", label: "Fichier de Schéma JSON", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "ignore_eos", label: "Ignorer Token EOS", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
    { name: "escape", label: "Échappement", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
    {
      name: "rope_scaling_type",
      label: "Type de Mise à l'Échelle ROPE",
      type: "select",
      options: ["", "linear", "yarn"],
      defaultValue: "",
      xs: 12,
      sm: 6,
    },
    { name: "rope_scale", label: "Échelle ROPE", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
    { name: "rope_freq_base", label: "Base Fréquence ROPE", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 100 },
    { name: "rope_freq_scale", label: "Échelle Fréquence ROPE", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
    {
      name: "yarn_orig_ctx",
      label: "Ctx Original YARN",
      type: "number",
      defaultValue: 0,
      xs: 12,
      sm: 6,
      unit: "tokens",
      step: 1,
    },
    { name: "yarn_ext_factor", label: "Facteur Extension YARN", type: "number", defaultValue: -1, xs: 12, sm: 6, unit: "", step: 1 },
    { name: "yarn_attn_factor", label: "Facteur Attention YARN", type: "number", defaultValue: 1, xs: 12, sm: 6, unit: "", step: 0.1 },
    { name: "yarn_beta_slow", label: "Beta Lent YARN", type: "number", defaultValue: 1, xs: 12, sm: 6, unit: "", step: 0.1 },
    { name: "yarn_beta_fast", label: "Beta Rapide YARN", type: "number", defaultValue: 32, xs: 12, sm: 6, unit: "", step: 1 },
    { name: "flash_attn", label: "Attention Flash", type: "select", options: ["", "0", "1"], defaultValue: "", xs: 12, sm: 6 },
    { name: "logit_bias", label: "Biais Logit", type: "text", defaultValue: "", xs: 12, sm: 6 },
  ],
  memory: [
    { name: "cache_ram", label: "Cache RAM", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "Go", step: 0.1 },
    { name: "cache_type_k", label: "Type de Cache K", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "cache_type_v", label: "Type de Cache V", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "mmap", label: "MMap (Cartographie Mémoire)", type: "boolean", defaultValue: true, xs: 12, sm: 6 },
    { name: "mlock", label: "MLock (Verrou Mémoire)", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
    { name: "numa", label: "NUMA", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "defrag_thold", label: "Seuil de Défragmentation", type: "number", defaultValue: -1, xs: 12, sm: 6, unit: "", step: 0.01 },
  ],
  gpu: [
    { name: "device", label: "Périphérique", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "list_devices", label: "Lister les Périphériques", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
    { name: "gpu_layers", label: "Couches GPU", type: "number", defaultValue: -1, xs: 12, sm: 6, unit: "couches", step: 1 },
    { name: "split_mode", label: "Mode de Partage", type: "select", options: ["", "layer", "row"], defaultValue: "", xs: 12, sm: 6 },
    { name: "tensor_split", label: "Répartition Tensor", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "main_gpu", label: "GPU Principal", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 1 },
    { name: "kv_offload", label: "Déchargement KV", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 1 },
    { name: "repack", label: "Réempaqueter", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
    { name: "no_host", label: "Pas d'Hôte", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
  ],
  advanced: [
    { name: "swa_full", label: "SWA Complet", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
    { name: "override_tensor", label: "Surcharger Tenseur", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "cpu_moe", label: "CPU MoE", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
    { name: "n_cpu_moe", label: "N CPU MoE", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 1 },
    { name: "kv_unified", label: "KV Unifié", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
    { name: "pooling", label: "Mise en Commun", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "context_shift", label: "Décalage de Contexte", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
    { name: "rpc", label: "RPC", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "offline", label: "Mode Hors Ligne", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
    { name: "override_kv", label: "Surcharger KV", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "op_offload", label: "Déchargement Op", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
    { name: "fit", label: "Ajuster", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "fit_target", label: "Cible d'Ajustement", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 1 },
    { name: "fit_ctx", label: "Contexte d'Ajustement", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "tokens", step: 1 },
    { name: "check_tensors", label: "Vérifier Tenseurs", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
    { name: "sleep_idle_seconds", label: "Secondes de Veille", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "s", step: 1 },
    { name: "polling", label: "Interrogation", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "polling_batch", label: "Traitement par Lot", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "reasoning_format", label: "Format de Raisonnement", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "reasoning_budget", label: "Budget de Raisonnement", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "tokens", step: 1 },
    { name: "custom_params", label: "Paramètres Personnalisés", type: "text", defaultValue: "", xs: 12, sm: 6 },
  ],
  lora: [
    { name: "lora", label: "LoRA", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "lora_scaled", label: "LoRA Mis à l'Échelle", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "control_vector", label: "Vecteur de Contrôle", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "control_vector_scaled", label: "Vecteur de Contrôle Mis à l'Échelle", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "control_vector_layer_range", label: "Plage de Couches Vecteur de Contrôle", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "model_draft", label: "Modèle de Brouillon", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "model_url_draft", label: "URL du Modèle de Brouillon", type: "text", defaultValue: "", xs: 12, sm: 6 },
    {
      name: "ctx_size_draft",
      label: "Taille du Contexte de Brouillon",
      type: "number",
      defaultValue: 0,
      xs: 12,
      sm: 6,
      unit: "tokens",
      step: 1,
    },
    { name: "threads_draft", label: "Threads de Brouillon", type: "number", defaultValue: -1, xs: 12, sm: 6, unit: "", step: 1 },
    { name: "threads_batch_draft", label: "Threads par Lot de Brouillon", type: "number", defaultValue: -1, xs: 12, sm: 6, unit: "", step: 1 },
    { name: "draft_max", label: "Brouillon Maximum", type: "number", defaultValue: 16, xs: 12, sm: 6, unit: "tokens", step: 1 },
    { name: "draft_min", label: "Brouillon Minimum", type: "number", defaultValue: 5, xs: 12, sm: 6, unit: "tokens", step: 1 },
    { name: "draft_p_min", label: "P Min de Brouillon", type: "number", defaultValue: 0.05, xs: 12, sm: 6, unit: "", step: 0.01 },
    { name: "cache_type_k_draft", label: "Type de Cache K Brouillon", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "cache_type_v_draft", label: "Type de Cache V Brouillon", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "cpu_moe_draft", label: "CPU MoE Brouillon", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 1 },
    { name: "n_cpu_moe_draft", label: "N CPU MoE Brouillon", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 1 },
    {
      name: "n_gpu_layers_draft",
      label: "N Couches GPU Brouillon",
      type: "number",
      defaultValue: -1,
      xs: 12,
      sm: 6,
      unit: "couches",
      step: 1,
    },
    { name: "device_draft", label: "Périphérique Brouillon", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "spec_replace", label: "Remplacement Spéculatif", type: "text", defaultValue: "", xs: 12, sm: 6 },
  ],
  multimodal: [
    { name: "mmproj", label: "Projecteur Multimodal", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "mmproj_url", label: "URL du Projecteur Multimodal", type: "text", defaultValue: "", xs: 12, sm: 6 },
    { name: "mmproj_auto", label: "Détection Auto MMPROJ", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
    { name: "mmproj_offload", label: "Déchargement MMPROJ", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
    { name: "image_min_tokens", label: "Tokens Min d'Image", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "tokens", step: 1 },
    { name: "image_max_tokens", label: "Tokens Max d'Image", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "tokens", step: 1 },
  ],
};
