"use client";
import React from "react";
import type { SvgIconTypeMap } from "@mui/material";
import {
  Speed as SpeedIcon,
  Memory as MemoryIcon,
  Settings as SettingsIcon,
  Tune as TuneIcon,
  Layers as LayersIcon,
} from "@mui/icons-material";
import type { ConfigType, FieldDefinition, SectionGroup, ValidationRule } from "./types";
// Create icon elements factory
type IconComponentType = React.ComponentType<SvgIconTypeMap["props"]>;
const createIcon = (IconComponent: IconComponentType): React.ReactElement =>
  React.createElement(IconComponent);
// Section groups for sampling configuration
export const modelSectionGroups: SectionGroup[] = [
  {
    title: "Échantillonnage Principal",
    icon: createIcon(SpeedIcon),
    fields: ["temperature", "top_k", "top_p", "min_p", "typical_p"],
  },
  {
    title: "Contrôle de Répétition",
    icon: createIcon(TuneIcon),
    fields: [
      "repeat_last_n",
      "repeat_penalty",
      "presence_penalty",
      "frequency_penalty",
    ],
  },
  {
    title: "Échantillonnage Avancé",
    icon: createIcon(SettingsIcon),
    fields: ["mirostat", "mirostat_eta", "mirostat_tau", "dynatemp_range", "dynatemp_exponent"],
  },
  {
    title: "Contraintes de Sortie",
    icon: createIcon(LayersIcon),
    fields: ["samplers", "sampler_seq", "seed", "grammar", "grammar_file"],
  },
  {
    title: "Extension de Contexte (ROPE)",
    icon: createIcon(MemoryIcon),
    fields: [
      "rope_scaling_type",
      "rope_scale",
      "rope_freq_base",
      "rope_freq_scale",
      "yarn_orig_ctx",
      "yarn_ext_factor",
      "yarn_attn_factor",
      "yarn_beta_slow",
      "yarn_beta_fast",
    ],
  },
];
// Validation rules for model sampling fields
export const modelValidationRules: Record<string, ValidationRule> = {
  temperature: { min: 0, max: 2, required: false },
  top_k: { min: 1, max: 100, required: false },
  top_p: { min: 0, max: 1, required: false },
  min_p: { min: 0, max: 0.5, required: false },
  typical_p: { min: 0.1, max: 1, required: false },
  repeat_last_n: { min: 0, max: 2048, required: false },
  repeat_penalty: { min: 1, max: 2, required: false },
  presence_penalty: { min: 0, max: 2, required: false },
  frequency_penalty: { min: 0, max: 2, required: false },
  mirostat: { min: 0, max: 2, required: false },
  mirostat_eta: { min: 0.001, max: 1, required: false },
  mirostat_tau: { min: 0, max: 10, required: false },
  dynatemp_range: { min: 0, max: 2, required: false },
  dynatemp_exponent: { min: 0.1, max: 2, required: false },
  seed: { min: -1, max: Number.MAX_SAFE_INTEGER, required: false },
  rope_scale: { min: 0, max: 10, required: false },
  rope_freq_base: { min: 0, max: 1000000, required: false },
  rope_freq_scale: { min: 0, max: 10, required: false },
  yarn_orig_ctx: { min: 0, max: 32768, required: false },
  yarn_ext_factor: { min: -1, max: 16, required: false },
  yarn_attn_factor: { min: 0, max: 4, required: false },
  yarn_beta_slow: { min: 0, max: 10, required: false },
  yarn_beta_fast: { min: 0, max: 100, required: false },
};
// Field definitions for model configuration
export const modelConfigFields: FieldDefinition[] = [
  {
    name: "temperature",
    label: "Température",
    type: "number",
    defaultValue: 0.7,
    xs: 12,
    sm: 6,
    unit: "",
    step: 0.01,
    marks: [
      { value: 0, label: "0" },
      { value: 1, label: "1" },
      { value: 2, label: "2" },
    ],
  },
  { name: "top_k", label: "Top K", type: "number", defaultValue: 40, xs: 12, sm: 6, unit: "", step: 1 },
  {
    name: "top_p",
    label: "Top P",
    type: "number",
    defaultValue: 0.9,
    xs: 12,
    sm: 6,
    unit: "",
    step: 0.01,
    marks: [
      { value: 0, label: "0" },
      { value: 1, label: "1" },
    ],
  },
  { name: "min_p", label: "Min P", type: "number", defaultValue: 0.05, xs: 12, sm: 6, unit: "", step: 0.01 },
  {
    name: "typical_p",
    label: "Typical P",
    type: "number",
    defaultValue: 1,
    xs: 12,
    sm: 6,
    unit: "",
    step: 0.01,
    marks: [
      { value: 0, label: "0" },
      { value: 1, label: "1" },
    ],
  },
  {
    name: "repeat_last_n",
    label: "Répéter Dernier N",
    type: "number",
    defaultValue: 64,
    xs: 12,
    sm: 6,
    unit: "tokens",
    step: 1,
  },
  {
    name: "repeat_penalty",
    label: "Pénalité de Répétition",
    type: "number",
    defaultValue: 1,
    xs: 12,
    sm: 6,
    unit: "",
    step: 0.01,
    marks: [
      { value: 1, label: "1.0" },
      { value: 1.5, label: "1.5" },
      { value: 2, label: "2.0" },
    ],
  },
  { name: "presence_penalty", label: "Pénalité de Présence", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "frequency_penalty", label: "Pénalité de Fréquence", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "dynatemp_range", label: "Plage Dynatemp", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "dynatemp_exp", label: "Exp Dynatemp", type: "number", defaultValue: 1, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "mirostat", label: "Mirostat", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 1 },
  { name: "mirostat_lr", label: "LR Mirostat", type: "number", defaultValue: 0.1, xs: 12, sm: 6, unit: "", step: 0.01 },
  { name: "mirostat_ent", label: "Ent Mirostat", type: "number", defaultValue: 5, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "samplers", label: "Échantillonneurs", type: "text", defaultValue: "", xs: 12 },
  { name: "sampler_seq", label: "Séquence d'Échantillonnage", type: "text", defaultValue: "", xs: 12 },
  { name: "seed", label: "Graine", type: "number", defaultValue: -1, xs: 12, sm: 6, unit: "", step: 1 },
  { name: "grammar", label: "Grammaire", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "grammar_file", label: "Fichier de Grammaire", type: "text", defaultValue: "", xs: 12, sm: 6 },
  {
    name: "rope_scaling_type",
    label: "Type de Mise à l'Échelle ROPE",
    type: "select",
    options: ["", "linear", "yarn"],
    defaultValue: "",
    xs: 12,
    sm: 6,
  },
  { name: "rope_scale", label: "Échelle ROPE", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "rope_freq_base", label: "Base Fréquence ROPE", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 100 },
  { name: "rope_freq_scale", label: "Échelle Fréquence ROPE", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
  {
    name: "yarn_orig_ctx",
    label: "Ctx Original YARN",
    type: "number",
    defaultValue: 0,
    xs: 12,
    sm: 6,
    unit: "tokens",
    step: 1,
  },
  { name: "yarn_ext_factor", label: "Facteur Extension YARN", type: "number", defaultValue: -1, xs: 12, sm: 6, unit: "", step: 1 },
  { name: "yarn_attn_factor", label: "Facteur Attention YARN", type: "number", defaultValue: 1, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "yarn_beta_slow", label: "Beta Lent YARN", type: "number", defaultValue: 1, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "yarn_beta_fast", label: "Beta Rapide YARN", type: "number", defaultValue: 32, xs: 12, sm: 6, unit: "", step: 1 },
];
