import { z } from "zod";

// ============================================================================
// TypeScript Interfaces
// ============================================================================
export interface SamplingConfig { temperature: number; top_p: number; top_k: number; min_p: number; typical_p: number; repeat_penalty: number; repeat_last_n: number; frequency_penalty: number; presence_penalty: number; mirostat: number; mirostat_tau: number; mirostat_eta: number; seed: number; flash_attn: "auto" | "on" | "off"; }
export interface MemoryConfig { ctx_size: number; num_batch: number; cache_ram: number; memory_f16: boolean; memory_lock: boolean; mmap: boolean; mlock: boolean; numa: string; defrag_thold: number; cache_type_k: string; cache_type_v: string; }
export interface GPUConfig { n_gpu_layers: number; n_gpu: number; tensor_split: string; main_gpu: number; mm_lock: boolean; list_devices: boolean; kv_offload: boolean; repack: boolean; no_host: boolean; split_mode: string; device: string; }
export interface AdvancedConfig { rope_frequency: number; rope_scale: number; yarn_ext_factor: number; yarn_orig_ctx: number; yarn_attn_factor: number; yarn_beta_fast: number; yarn_beta_slow: number; num_thread: number; num_predict: number; swa_full: boolean; override_tensor: string; cpu_moe: boolean; n_cpu_moe: number; kv_unified: boolean; context_shift: boolean; rpc: string; offline: boolean; override_kv: string; op_offload: boolean; check_tensors: boolean; }
export interface LoRAConfig { lora_adapter: string; lora_base: string; lora_scale: number; control_vectors: string; }
export interface MultimodalConfig { image_data: string; clip_vision_cache: boolean; mmproj: string; mmproj_auto: boolean; mmproj_offload: boolean; }
export type ConfigType = "sampling" | "memory" | "gpu" | "advanced" | "lora" | "multimodal";

// ============================================================================
// Zod Validation Schemas
// ============================================================================
export const samplingConfigSchema = z.object({ temperature: z.number().min(0).max(2).default(0.7), top_p: z.number().min(0).max(1).default(0.9), top_k: z.number().min(0).max(100).default(40), min_p: z.number().min(0).max(0.5).default(0.05), typical_p: z.number().min(0.1).max(1).default(1.0), repeat_penalty: z.number().min(1).max(2).default(1.1), repeat_last_n: z.number().min(0).max(2048).default(64), frequency_penalty: z.number().min(0).max(2).default(0), presence_penalty: z.number().min(0).max(2).default(0), mirostat: z.number().min(0).max(2).default(0), mirostat_tau: z.number().min(0).max(10).default(5.0), mirostat_eta: z.number().min(0).max(1).default(0.1), seed: z.number().int().min(-1).max(2147483647).default(-1), flash_attn: z.enum(["auto", "on", "off"]).default("auto") });
export const memoryConfigSchema = z.object({ ctx_size: z.number().min(1).default(2048), num_batch: z.number().min(1).default(512), cache_ram: z.number().min(0).default(0), memory_f16: z.boolean().default(true), memory_lock: z.boolean().default(false), mmap: z.boolean().default(false), mlock: z.boolean().default(false), numa: z.string().default(""), defrag_thold: z.number().min(-1).max(1).default(-1), cache_type_k: z.string().default("f16"), cache_type_v: z.string().default("f16") });
export const gpuConfigSchema = z.object({ n_gpu_layers: z.number().min(-1).max(1000).default(-1), n_gpu: z.number().min(1).max(16).default(1), tensor_split: z.string().default(""), main_gpu: z.number().min(0).max(16).default(0), mm_lock: z.boolean().default(false), list_devices: z.boolean().default(false), kv_offload: z.boolean().default(false), repack: z.boolean().default(false), no_host: z.boolean().default(false), split_mode: z.enum(["", "layer", "row"]).default("layer"), device: z.string().default("") });
export const advancedConfigSchema = z.object({ rope_frequency: z.number().min(1).max(1000000).default(10000), rope_scale: z.number().min(0).max(10).default(1.0), yarn_ext_factor: z.number().min(-1).max(16).default(-1), yarn_orig_ctx: z.number().min(0).max(32768).default(0), yarn_attn_factor: z.number().min(0).max(4).default(1.0), yarn_beta_fast: z.number().min(0).max(100).default(32), yarn_beta_slow: z.number().min(0).max(10).default(1), num_thread: z.number().min(1).default(8), num_predict: z.number().min(-1).default(-1), swa_full: z.boolean().default(false), override_tensor: z.string().default(""), cpu_moe: z.boolean().default(false), n_cpu_moe: z.number().min(0).max(64).default(0), kv_unified: z.boolean().default(false), context_shift: z.boolean().default(false), rpc: z.string().default(""), offline: z.boolean().default(false), override_kv: z.string().default(""), op_offload: z.boolean().default(false), check_tensors: z.boolean().default(false) });
export const loraConfigSchema = z.object({ lora_adapter: z.string().default(""), lora_base: z.string().default(""), lora_scale: z.number().min(0).max(1).default(1.0), control_vectors: z.string().default("") });
export const multimodalConfigSchema = z.object({ image_data: z.string().default(""), clip_vision_cache: z.boolean().default(false), mmproj: z.string().default(""), mmproj_auto: z.boolean().default(false), mmproj_offload: z.boolean().default(false) });

// ============================================================================
// Section Groups for UI Organization
// ============================================================================
export const sectionGroups: Record<ConfigType, Array<{ title: string; fields: string[] }>> = {
  sampling: [{ title: "Core Sampling", fields: ["temperature", "top_k", "top_p", "min_p", "typical_p"] }, { title: "Repetition Control", fields: ["repeat_last_n", "repeat_penalty", "frequency_penalty", "presence_penalty"] }, { title: "Mirostat Sampling", fields: ["mirostat", "mirostat_tau", "mirostat_eta"] }, { title: "Output Control", fields: ["seed", "flash_attn"] }],
  memory: [{ title: "Cache Settings", fields: ["cache_ram", "cache_type_k", "cache_type_v"] }, { title: "Memory Management", fields: ["mmap", "mlock", "numa", "defrag_thold"] }],
  gpu: [{ title: "Device Selection", fields: ["device", "list_devices"] }, { title: "GPU Configuration", fields: ["n_gpu_layers", "split_mode", "tensor_split", "main_gpu", "kv_offload"] }, { title: "Performance", fields: ["repack", "no_host"] }],
  advanced: [{ title: "ROPE Scaling", fields: ["rope_frequency", "rope_scale"] }, { title: "YaRN Context", fields: ["yarn_ext_factor", "yarn_orig_ctx", "yarn_attn_factor", "yarn_beta_fast", "yarn_beta_slow"] }, { title: "Model Behavior", fields: ["swa_full", "override_tensor", "cpu_moe", "n_cpu_moe", "kv_unified", "context_shift"] }, { title: "Distributed", fields: ["rpc", "offline", "override_kv", "op_offload", "check_tensors"] }],
  lora: [{ title: "LoRA Configuration", fields: ["lora_adapter", "lora_base", "lora_scale"] }, { title: "Control Vectors", fields: ["control_vectors"] }],
  multimodal: [{ title: "Multimodal Projection", fields: ["mmproj", "mmproj_auto", "mmproj_offload"] }, { title: "Image Processing", fields: ["image_data", "clip_vision_cache"] }],
};
