import { TooltipContent } from "./tooltip-config.types";

export const dryTooltips: Record<string, TooltipContent> = {
  dry_multiplier: {
    title: "DRY Multiplier",
    description: "Multiplier for DRY (Don't Repeat Yourself) sampling to penalize repeated n-grams.",
    recommendedValue: "0.0 - 5.0 (default: 0)",
    effectOnModel: "Controls strength of DRY repetition penalty. Higher values reduce repetition more aggressively.",
    whenToAdjust: "Enable when model repeats phrases or sentences.",
  },
  dry_base: {
    title: "DRY Base",
    description: "Base value for DRY penalty calculation.",
    recommendedValue: "1.0 - 3.0 (default: 1.75)",
    effectOnModel: "Adjusts the base penalty calculation for repeated content.",
    whenToAdjust: "Fine-tune in conjunction with DRY multiplier for optimal repetition control.",
  },
  dry_allowed_length: {
    title: "DRY Allowed Length",
    description: "Minimum length of repeated sequences to apply DRY penalty.",
    recommendedValue: "0 - 10 (default: 2)",
    effectOnModel: "Only penalizes repetitions longer than this value.",
    whenToAdjust: "Increase to allow short repetitions, decrease to catch more repetitions.",
  },
  dry_penalty_last_n: {
    title: "DRY Penalty Last N",
    description: "Number of tokens to look back when applying DRY penalty.",
    recommendedValue: "0 - 512 (default: 0)",
    effectOnModel: "Controls the context window for DRY repetition detection.",
    whenToAdjust: "Increase to detect longer-range repetitions.",
  },
  dry_sequence_breaker: {
    title: "DRY Sequence Breaker",
    description: "Characters that break sequences for DRY penalty calculation.",
    recommendedValue: "\\n, !, ., ? (default: \\n, !, ., ?)",
    effectOnModel: "Separates text into chunks at these characters when detecting repetitions.",
    whenToAdjust: "Customize based on language and text structure.",
  },
  dynatemp_range: {
    title: "Dynatemp Range",
    description: "Range for dynamic temperature adjustment during generation.",
    recommendedValue: "0.0 - 2.0 (default: 0)",
    effectOnModel: "Enables temperature to vary dynamically within this range for more varied outputs.",
    whenToAdjust: "Enable when you want varied creativity throughout the response.",
  },
  dynatemp_exponent: {
    title: "Dynatemp Exponent",
    description: "Exponent for dynamic temperature curve shape.",
    recommendedValue: "0.1 - 2.0 (default: 1)",
    effectOnModel: "Controls the distribution shape of dynamic temperature values.",
    whenToAdjust: "Fine-tune with dynatemp_range for desired dynamic behavior.",
  },
};

export const ropeScalingTooltips: Record<string, TooltipContent> = {
  rope_scaling_type: {
    title: "ROPE Scaling Type",
    description: "Method for extending context window using ROPE (Rotary Position Embedding).",
    recommendedValue: "empty, linear, or yarn (default: empty)",
    effectOnModel: "Extends context window beyond model's original limit. YARN is more advanced.",
    whenToAdjust: "Use when you need longer context than model natively supports.",
  },
  rope_scale: {
    title: "ROPE Scale",
    description: "Scaling factor for ROPE position embeddings.",
    recommendedValue: "0.0 - 10.0 (default: 0)",
    effectOnModel: "Scales the context window. 1.0 = no scaling.",
    whenToAdjust: "Set >1.0 to extend context window.",
  },
  rope_freq_base: {
    title: "ROPE Frequency Base",
    description: "Base frequency for ROPE position embeddings.",
    recommendedValue: "0 - 1000000 (default: 0)",
    effectOnModel: "Adjusts the frequency base for position encoding.",
    whenToAdjust: "Adjust in conjunction with ROPE scaling for optimal results.",
  },
  rope_freq_scale: {
    title: "ROPE Frequency Scale",
    description: "Frequency scaling factor for ROPE.",
    recommendedValue: "0.0 - 10.0 (default: 0)",
    effectOnModel: "Scales position frequencies for context extension.",
    whenToAdjust: "Use with ROPE scaling for fine-tuning context extension.",
  },
  yarn_orig_ctx: {
    title: "YARN Original Context",
    description: "Original context size for YARN scaling.",
    recommendedValue: "0 - 32768 (default: 0)",
    effectOnModel: "Sets the base context size for YARN scaling calculation.",
    whenToAdjust: "Set to model's original context size when using YARN.",
  },
  yarn_ext_factor: {
    title: "YARN Extension Factor",
    description: "Factor by which to extend context with YARN.",
    recommendedValue: "-1 to 16 (default: -1)",
    effectOnModel: "Controls context extension factor. -1 uses auto-detection.",
    whenToAdjust: "Set explicitly when auto-detection doesn't work well.",
  },
  yarn_attn_factor: {
    title: "YARN Attention Factor",
    description: "Attention factor for YARN scaling.",
    recommendedValue: "0.0 - 4.0 (default: 1)",
    effectOnModel: "Adjusts attention in extended context.",
    whenToAdjust: "Fine-tune for better performance on extended context.",
  },
  yarn_beta_slow: {
    title: "YARN Beta Slow",
    description: "Slow beta parameter for YARN.",
    recommendedValue: "0.0 - 10.0 (default: 1)",
    effectOnModel: "Controls slow component of YARN interpolation.",
    whenToAdjust: "Adjust for optimal extended context quality.",
  },
  yarn_beta_fast: {
    title: "YARN Beta Fast",
    description: "Fast beta parameter for YARN.",
    recommendedValue: "0.0 - 100.0 (default: 32)",
    effectOnModel: "Controls fast component of YARN interpolation.",
    whenToAdjust: "Adjust with yarn_beta_slow for best results.",
  },
  flash_attn: {
    title: "Flash Attention",
    description: "Enables Flash Attention implementation for faster inference. 0=off, 1=on.",
    recommendedValue: "0 or 1 (default: empty)",
    effectOnModel: "Significantly speeds up attention computation when supported by hardware.",
    whenToAdjust: "Enable if your GPU supports Flash Attention for faster generation.",
  },
  logit_bias: {
    title: "Logit Bias",
    description: "Comma-separated list of token biases in format token_id:bias.",
    recommendedValue: "e.g., 123:2.0,456:-1.0",
    effectOnModel: "Manually adjust probabilities of specific tokens.",
    whenToAdjust: "Use to encourage or discourage specific words or tokens.",
  },
};
