"use client";

import type { FieldDefinition } from "../../components/ui/ModelConfigDialog/types";

// Advanced configuration fields - advanced settings, LoRA, and multimodal
export const advancedFields: FieldDefinition[] = [
  { name: "swa_full", label: "SWA Complet", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
  { name: "override_tensor", label: "Surcharger Tenseur", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "cpu_moe", label: "CPU MoE", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
  { name: "n_cpu_moe", label: "N CPU MoE", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 1 },
  { name: "kv_unified", label: "KV Unifié", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
  { name: "pooling", label: "Mise en Commun", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "context_shift", label: "Décalage de Contexte", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
  { name: "rpc", label: "RPC", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "offline", label: "Mode Hors Ligne", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
  { name: "override_kv", label: "Surcharger KV", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "op_offload", label: "Déchargement Op", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
  { name: "fit", label: "Ajuster", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "fit_target", label: "Cible d'Ajustement", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 1 },
  { name: "fit_ctx", label: "Contexte d'Ajustement", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "tokens", step: 1 },
  { name: "check_tensors", label: "Vérifier Tenseurs", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
  { name: "sleep_idle_seconds", label: "Secondes de Veille", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "s", step: 1 },
  { name: "polling", label: "Interrogation", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "polling_batch", label: "Traitement par Lot", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "reasoning_format", label: "Format de Raisonnement", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "reasoning_budget", label: "Budget de Raisonnement", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "tokens", step: 1 },
  { name: "custom_params", label: "Paramètres Personnalisés", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "lora", label: "LoRA", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "lora_scaled", label: "LoRA Mis à l'Échelle", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "control_vector", label: "Vecteur de Contrôle", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "control_vector_scaled", label: "Vecteur de Contrôle Mis à l'Échelle", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "control_vector_layer_range", label: "Plage de Couches Vecteur de Contrôle", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "model_draft", label: "Modèle de Brouillon", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "model_url_draft", label: "URL du Modèle de Brouillon", type: "text", defaultValue: "", xs: 12, sm: 6 },
  {
    name: "ctx_size_draft",
    label: "Taille du Contexte de Brouillon",
    type: "number",
    defaultValue: 0,
    xs: 12,
    sm: 6,
    unit: "tokens",
    step: 1,
  },
  { name: "threads_draft", label: "Threads de Brouillon", type: "number", defaultValue: -1, xs: 12, sm: 6, unit: "", step: 1 },
  { name: "threads_batch_draft", label: "Threads par Lot de Brouillon", type: "number", defaultValue: -1, xs: 12, sm: 6, unit: "", step: 1 },
  { name: "draft_max", label: "Brouillon Maximum", type: "number", defaultValue: 16, xs: 12, sm: 6, unit: "tokens", step: 1 },
  { name: "draft_min", label: "Brouillon Minimum", type: "number", defaultValue: 5, xs: 12, sm: 6, unit: "tokens", step: 1 },
  { name: "draft_p_min", label: "P Min de Brouillon", type: "number", defaultValue: 0.05, xs: 12, sm: 6, unit: "", step: 0.01 },
  { name: "cache_type_k_draft", label: "Type de Cache K Brouillon", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "cache_type_v_draft", label: "Type de Cache V Brouillon", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "cpu_moe_draft", label: "CPU MoE Brouillon", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 1 },
  { name: "n_cpu_moe_draft", label: "N CPU MoE Brouillon", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 1 },
  {
    name: "n_gpu_layers_draft",
    label: "N Couches GPU Brouillon",
    type: "number",
    defaultValue: -1,
    xs: 12,
    sm: 6,
    unit: "couches",
    step: 1,
  },
  { name: "device_draft", label: "Périphérique Brouillon", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "spec_replace", label: "Remplacement Spéculatif", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "mmproj", label: "Projecteur Multimodal", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "mmproj_url", label: "URL du Projecteur Multimodal", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "mmproj_auto", label: "Détection Auto MMPROJ", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
  { name: "mmproj_offload", label: "Déchargement MMPROJ", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
  { name: "image_min_tokens", label: "Tokens Min d'Image", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "tokens", step: 1 },
  { name: "image_max_tokens", label: "Tokens Max d'Image", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "tokens", step: 1 },
];
