"use client";

import type { FieldDefinition } from "../../components/ui/ModelConfigDialog/types";

// Inference/sampling fields for text generation
export const inferenceFields: FieldDefinition[] = [
  {
    name: "temperature",
    label: "Température",
    type: "number",
    defaultValue: 0.7,
    xs: 12,
    sm: 6,
    unit: "",
    step: 0.01,
    marks: [
      { value: 0, label: "0" },
      { value: 1, label: "1" },
      { value: 2, label: "2" },
    ],
  },
  { name: "top_k", label: "Top K", type: "number", defaultValue: 40, xs: 12, sm: 6, unit: "", step: 1 },
  {
    name: "top_p",
    label: "Top P",
    type: "number",
    defaultValue: 0.9,
    xs: 12,
    sm: 6,
    unit: "",
    step: 0.01,
    marks: [
      { value: 0, label: "0" },
      { value: 1, label: "1" },
    ],
  },
  { name: "min_p", label: "Min P", type: "number", defaultValue: 0.05, xs: 12, sm: 6, unit: "", step: 0.01 },
  { name: "top_nsigma", label: "Top N Sigma", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
  {
    name: "xtc_probability",
    label: "Probabilité XTC",
    type: "number",
    defaultValue: 0,
    xs: 12,
    sm: 6,
    unit: "",
    step: 0.01,
    marks: [
      { value: 0, label: "0" },
      { value: 1, label: "1" },
    ],
  },
  { name: "xtc_threshold", label: "Seuil XTC", type: "number", defaultValue: 0.1, xs: 12, sm: 6, unit: "", step: 0.01 },
  {
    name: "typical_p",
    label: "Typical P",
    type: "number",
    defaultValue: 1,
    xs: 12,
    sm: 6,
    unit: "",
    step: 0.01,
    marks: [
      { value: 0, label: "0" },
      { value: 1, label: "1" },
    ],
  },
  {
    name: "repeat_last_n",
    label: "Répéter Dernier N",
    type: "number",
    defaultValue: 64,
    xs: 12,
    sm: 6,
    unit: "tokens",
    step: 1,
  },
  {
    name: "repeat_penalty",
    label: "Pénalité de Répétition",
    type: "number",
    defaultValue: 1,
    xs: 12,
    sm: 6,
    unit: "",
    step: 0.01,
    marks: [
      { value: 1, label: "1.0" },
      { value: 1.5, label: "1.5" },
      { value: 2, label: "2.0" },
    ],
  },
  { name: "presence_penalty", label: "Pénalité de Présence", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "frequency_penalty", label: "Pénalité de Fréquence", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "dry_multiplier", label: "Multiplicateur DRY", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "dry_base", label: "Base DRY", type: "number", defaultValue: 1.75, xs: 12, sm: 6, unit: "", step: 0.01 },
  {
    name: "dry_allowed_length",
    label: "Longueur Autorisée DRY",
    type: "number",
    defaultValue: 2,
    xs: 12,
    sm: 6,
    unit: "tokens",
    step: 1,
  },
  {
    name: "dry_penalty_last_n",
    label: "Pénalité Dernier N DRY",
    type: "number",
    defaultValue: 0,
    xs: 12,
    sm: 6,
    unit: "tokens",
    step: 1,
  },
  { name: "dry_sequence_breaker", label: "Séparateur de Séquence DRY", type: "text", defaultValue: "\\n, !, ., ?", xs: 12, sm: 6 },
  { name: "dynatemp_range", label: "Plage Dynatemp", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "dynatemp_exp", label: "Exp Dynatemp", type: "number", defaultValue: 1, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "mirostat", label: "Mirostat", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 1 },
  { name: "mirostat_lr", label: "LR Mirostat", type: "number", defaultValue: 0.1, xs: 12, sm: 6, unit: "", step: 0.01 },
  { name: "mirostat_ent", label: "Ent Mirostat", type: "number", defaultValue: 5, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "samplers", label: "Échantillonneurs", type: "text", defaultValue: "", xs: 12 },
  { name: "sampler_seq", label: "Séquence d'Échantillonnage", type: "text", defaultValue: "", xs: 12 },
  { name: "seed", label: "Graine", type: "number", defaultValue: -1, xs: 12, sm: 6, unit: "", step: 1 },
  { name: "grammar", label: "Grammaire", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "grammar_file", label: "Fichier de Grammaire", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "json_schema", label: "Schéma JSON", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "json_schema_file", label: "Fichier de Schéma JSON", type: "text", defaultValue: "", xs: 12, sm: 6 },
  { name: "ignore_eos", label: "Ignorer Token EOS", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
  { name: "escape", label: "Échappement", type: "boolean", defaultValue: false, xs: 12, sm: 6 },
  {
    name: "rope_scaling_type",
    label: "Type de Mise à l'Échelle ROPE",
    type: "select",
    options: ["", "linear", "yarn"],
    defaultValue: "",
    xs: 12,
    sm: 6,
  },
  { name: "rope_scale", label: "Échelle ROPE", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "rope_freq_base", label: "Base Fréquence ROPE", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 100 },
  { name: "rope_freq_scale", label: "Échelle Fréquence ROPE", type: "number", defaultValue: 0, xs: 12, sm: 6, unit: "", step: 0.1 },
  {
    name: "yarn_orig_ctx",
    label: "Ctx Original YARN",
    type: "number",
    defaultValue: 0,
    xs: 12,
    sm: 6,
    unit: "tokens",
    step: 1,
  },
  { name: "yarn_ext_factor", label: "Facteur Extension YARN", type: "number", defaultValue: -1, xs: 12, sm: 6, unit: "", step: 1 },
  { name: "yarn_attn_factor", label: "Facteur Attention YARN", type: "number", defaultValue: 1, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "yarn_beta_slow", label: "Beta Lent YARN", type: "number", defaultValue: 1, xs: 12, sm: 6, unit: "", step: 0.1 },
  { name: "yarn_beta_fast", label: "Beta Rapide YARN", type: "number", defaultValue: 32, xs: 12, sm: 6, unit: "", step: 1 },
  { name: "flash_attn", label: "Attention Flash", type: "select", options: ["", "0", "1"], defaultValue: "", xs: 12, sm: 6 },
  { name: "logit_bias", label: "Biais Logit", type: "text", defaultValue: "", xs: 12, sm: 6 },
];
